### ISSUE TITLE
Regression in xmlValidation option

### ISSUE THREAD

**Issue by rdicroce** [alexnederlof/Jasper-report-maven-plugin#50] opened 2018-11-15 18:27 UTC
The conversion to Mojo annotations introduced a bug in the xmlValidation option. The default value is supposed to be "true" but is instead "tue". For me, this causes SAXParser exceptions.

Workaround: explicitly set xmlValidation to "true" in your POM.

**Comment by tan9** [comment] 2019-01-03 06:17
@alexnederlof I can confirm this issue will break report compilation as following:

```
 Could not compile my_report.jrxml because Error creating SAX parser.
net.sf.jasperreports.engine.JRRuntimeException: Error creating SAX parser.
    at net.sf.jasperreports.engine.xml.BaseSaxParserFactory.createParser (BaseSaxParserFactory.java:123)
    at net.sf.jasperreports.engine.xml.JRXmlDigesterFactory.createParser (JRXmlDigesterFactory.java:1597)
    at net.sf.jasperreports.engine.xml.JRXmlDigesterFactory.createDigester (JRXmlDigesterFactory.java:1566)
    at net.sf.jasperreports.engine.xml.JRXmlLoader.load (JRXmlLoader.java:263)
    at net.sf.jasperreports.engine.xml.JRXmlLoader.load (JRXmlLoader.java:248)
    at net.sf.jasperreports.engine.JasperCompileManager.compileToStream (JasperCompileManager.java:307)
    at net.sf.jasperreports.engine.JasperCompileManager.compileReportToStream (JasperCompileManager.java:587)
    at com.alexnederlof.jasperreport.CompileTask.call (CompileTask.java:63)
    at com.alexnederlof.jasperreport.CompileTask.call (CompileTask.java:28)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Caused by: org.xml.sax.SAXNotSupportedException: Property 'http://java.sun.com/xml/jaxp/properties/schemaLanguage' must be set before setting property 'http://java.sun.com/xml/jaxp/properties/schemaSource'. 
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.setProperty (SAXParserImpl.java:554)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.setProperty (SAXParserImpl.java:303)
    at net.sf.jasperreports.engine.xml.BaseSaxParserFactory.configureParser (BaseSaxParserFactory.java:166)
```

Although the workaround provided by @rdicroce works for me, it is good to have it fixed from the origin.

**Comment by tan9** [comment] 2019-04-19 02:56
@alexnederlof , this issue can be close as of #51 has been merged.

**Closed** 2019-04-29 09:17 UTC
